ipex button
huggingface/optimum-intel pull request #881
Opened 2024-08-28 06:52 UTC by jiqing-feng

Add ipex button for better instruction.

2024-08-28 06:55 UTC, jiqing-feng commented
Hi @IlyasMoutawwakil , Could you please merge this PR since [ipex doc](https://github.com/huggingface/optimum-intel/pull/828) has been merged, it could help users to find ipex doc well. Thx!

2024-08-28 07:07 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-intel/pr_881). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-08-28 08:43 UTC, sywangyi approved these changes

2024-08-28 08:54 UTC, IlyasMoutawwakil approved these changes

2024-08-28 09:17 UTC, echarlaix requested changes
Do you know when we can start the refactorization with torch.compile ? This will lead to a lot of modifications for the ipex integration + model exported via TorchScript getting deprecated, so I'd be in favor to add the ipex button only after the planned refactorization

2024-09-12 10:29 UTC, echarlaix approved these changes

2024-09-12 10:29 UTC, merged